command: /usr/bin/python /u/pedronis/PyPy/dist/pypy/tool/alarm.py 900 /u/pedronis/PyPy/dist/pypy/interpreter/py.py --oldstyle /u/pedronis/PyPy/dist/lib-python-2.3.4/test/test_binhex.py
run by: pedronis@ratthing-b246
sys.platform: linux2
sys.version_info: (2, 3, 5, 'final', 0)
startdate: Wed Apr 27 21:57:58 2005
pypy-revision: 11549
============================================================
faking <type 'unicode'>
faking <type 'module'>
faking <type 'file'>
faking <type 'posix.stat_result'>
faking <type 'posix.statvfs_result'>
Traceback (application-level):
  File "/u/pedronis/PyPy/dist/lib-python-2.3.4/test/test_binhex.py", line 49 in ?
    test_main()
  File "/u/pedronis/PyPy/dist/lib-python-2.3.4/test/test_binhex.py", line 45 in test_main
    test_support.run_unittest(BinHexTestCase)
  File "/u/pedronis/PyPy/dist/lib-python-2.3.4/test/test_support.py", line 262 in run_unittest
    run_suite(suite, testclass)
  File "/u/pedronis/PyPy/dist/lib-python-2.3.4/test/test_support.py", line 247 in run_suite
        raise TestFailed(err)
TestFailed: Traceback (most recent call last):
  File "/u/pedronis/PyPy/dist/lib-python-2.3.4/test/test_binhex.py", line 33, in test_binhex
    binhex.binhex(self.fname1, self.fname2)
  File "/u/pedronis/PyPy/dist/lib-python-2.3.4/binhex.py", line 260, in binhex
    ofp = BinHex(finfo, out)
  File "/u/pedronis/PyPy/dist/lib-python-2.3.4/binhex.py", line 196, in __init__
    self._writeinfo(name, finfo)
  File "/u/pedronis/PyPy/dist/lib-python-2.3.4/binhex.py", line 212, in _writeinfo
    self._writecrc()
  File "/u/pedronis/PyPy/dist/lib-python-2.3.4/binhex.py", line 221, in _writecrc
    self.ofp.write(struct.pack('>h', self.crc))
  File "/u/pedronis/PyPy/dist/pypy/lib/struct.py", line 293, in pack
    result += [format['pack'](var,format['size'],endianness)]
  File "/u/pedronis/PyPy/dist/pypy/lib/struct.py", line 111, in pack_signed_int
    raise OverflowError,"Number:%i to large to convert" % number
OverflowError: Number:51917 to large to convert

test_binhex (__main__.BinHexTestCase) ... ERROR

======================================================================
ERROR: test_binhex (__main__.BinHexTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/u/pedronis/PyPy/dist/lib-python-2.3.4/test/test_binhex.py", line 33, in test_binhex
    binhex.binhex(self.fname1, self.fname2)
  File "/u/pedronis/PyPy/dist/lib-python-2.3.4/binhex.py", line 260, in binhex
    ofp = BinHex(finfo, out)
  File "/u/pedronis/PyPy/dist/lib-python-2.3.4/binhex.py", line 196, in __init__
    self._writeinfo(name, finfo)
  File "/u/pedronis/PyPy/dist/lib-python-2.3.4/binhex.py", line 212, in _writeinfo
    self._writecrc()
  File "/u/pedronis/PyPy/dist/lib-python-2.3.4/binhex.py", line 221, in _writecrc
    self.ofp.write(struct.pack('>h', self.crc))
  File "/u/pedronis/PyPy/dist/pypy/lib/struct.py", line 293, in pack
    result += [format['pack'](var,format['size'],endianness)]
  File "/u/pedronis/PyPy/dist/pypy/lib/struct.py", line 111, in pack_signed_int
    raise OverflowError,"Number:%i to large to convert" % number
OverflowError: Number:51917 to large to convert

----------------------------------------------------------------------
Ran 1 test in 3.151s

FAILED (errors=1)
========================== closed ==========================
execution time: 9.49319386482 seconds
exit status: 1
