command: /usr/bin/python /home/arigo/pypysrc/pypy/tool/alarm.py 900 /home/arigo/pypysrc/pypy/interpreter/py.py --oldstyle /home/arigo/pypysrc/lib-python-2.3.4/test/test_email.py
run by: arigo@tismerysoft.de
sys.platform: linux2
sys.version_info: (2, 3, 5, 'final', 0)
startdate: Thu Apr 28 02:14:02 2005
pypy-revision: 11518
============================================================
faking <type 'unicode'>
faking <type 'module'>
faking <type 'file'>
faking <type 'posix.stat_result'>
faking <type 'posix.statvfs_result'>
Traceback (application-level):
  File "/home/arigo/pypysrc/lib-python-2.3.4/test/test_email.py", line 6 in ?
from email.test.test_email import suite
  File "/home/arigo/pypysrc/lib-python-2.3.4/email/__init__.py", line 69 in ?
from encodings.aliases import aliases # The aliases dictionary
  File "/home/arigo/pypysrc/lib-python-2.3.4/encodings/__init__.py", line 137 in ?
codecs.register(search_function)
TypeError: argument must be callable
========================== closed ==========================
execution time: 5.98763108253 seconds
exit status: 1
