command: /usr/bin/python /u/pedronis/PyPy/dist/pypy/tool/alarm.py 900 /u/pedronis/PyPy/dist/pypy/interpreter/py.py --oldstyle /u/pedronis/PyPy/dist/lib-python-2.3.4/test/test_dl.py
run by: pedronis@ratthing-b246
sys.platform: linux2
sys.version_info: (2, 3, 5, 'final', 0)
startdate: Wed Apr 27 23:53:55 2005
pypy-revision: 11549
============================================================
faking <type 'unicode'>
faking <type 'module'>
Traceback (application-level):
  File "/u/pedronis/PyPy/dist/lib-python-2.3.4/test/test_dl.py", line 6 in ?
import dl
ImportError: dl
========================== closed ==========================
execution time: 0.777956008911 seconds
exit status: 1
